version: '2'

services:
   dotfiles:
      container_name: dotfiles
      restart: always
      build:
        context: .
        args:
          USER_NAME: bsilva
      volumes:
         - ../docker-compose:/home/bsilva/youzz-development
      ports:
        - '2323:22'
