#!/bin/bash

echo 'pre-commiting'

git diff --cached --name-only | while read FILE; do
echo "$FILE"
if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
    # Courtesy of swytsh from the comments below.
    if [[ -f $FILE ]]; then
        echo $FILE
        if [ $? -ne 0 ]; then
            echo -e "\e[1;31m\tAborting commit due to files with syntax errors.\e[0m" >&2
            exit 1
        fi
        RESULT=$(grep "dpm(" "$FILE")
        if [ ! -z $RESULT ]; then
            echo -e "\e[1;33m\tWarning, the commit contains a call to dpm(). Commit was not aborted, however.\e[0m" >&2
        fi]])
    fi
fi
done #|| exit $?

exit 1
