alias docker="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker.exe"
alias docker-compose="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-compose.exe"
alias choco="/mnt/c/ProgramData/chocolatey/bin/choco.exe"
alias welixir="cmd.exe /c /mnt/c/ProgramData/chocolatey/lib/Elixir/bin/elixir.bat"
alias wmix="cmd.exe /c /mnt/c/ProgramData/chocolatey/lib/Elixir/bin/mix.bat"
